# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shark < Formula
  desc "Task management CLI for AI-driven development workflows"
  homepage "https://github.com/jwwelbor/shark-task-manager"
  version "1.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jwwelbor/shark-task-manager/releases/download/v1.5.3/shark_1.5.3_darwin_amd64.tar.gz"
      sha256 "3d81c6637047825fbd27630815dc72f3a3428e6860440ba2c0e7063b221ccd44"

      define_method(:install) do
        bin.install "shark"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jwwelbor/shark-task-manager/releases/download/v1.5.3/shark_1.5.3_darwin_arm64.tar.gz"
      sha256 "958e0855b67845093b085757345fc3c2ba96e01ae1e09ea506fff2573f7a69f7"

      define_method(:install) do
        bin.install "shark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwwelbor/shark-task-manager/releases/download/v1.5.3/shark_1.5.3_linux_amd64.tar.gz"
      sha256 "b508d26c39bdb369fa89203e8b1ff0e28deae9f18d705b178bee671c14c6b89f"
      define_method(:install) do
        bin.install "shark"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwwelbor/shark-task-manager/releases/download/v1.5.3/shark_1.5.3_linux_arm64.tar.gz"
      sha256 "12cc294d6de2247bedb107e6fd55e3a69c34694994c0a3aa0eb51de3c902eb9b"
      define_method(:install) do
        bin.install "shark"
      end
    end
  end

  test do
    system "#{bin}/shark", "--version"
  end
end
