# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shark < Formula
  desc "Task management CLI for AI-driven development workflows"
  homepage "https://github.com/jwwelbor/shark-task-manager"
  version "1.5.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jwwelbor/shark-task-manager/releases/download/v1.5.4/shark_1.5.4_darwin_amd64.tar.gz"
      sha256 "1ee6beb29d4b5e0ff14218a8584ee415b31c4fde185703079cf0dc2be80443d6"

      define_method(:install) do
        bin.install "shark"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jwwelbor/shark-task-manager/releases/download/v1.5.4/shark_1.5.4_darwin_arm64.tar.gz"
      sha256 "88df05ec6d33876dbbd5f22399a5ea89d116be86f3a86dfe65fa936de396efc6"

      define_method(:install) do
        bin.install "shark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwwelbor/shark-task-manager/releases/download/v1.5.4/shark_1.5.4_linux_amd64.tar.gz"
      sha256 "3e2a01d0358f311c06c84bb716960d43e48048a9656c6519c5aef119812fba85"
      define_method(:install) do
        bin.install "shark"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwwelbor/shark-task-manager/releases/download/v1.5.4/shark_1.5.4_linux_arm64.tar.gz"
      sha256 "06a8d7079e21c65771eae367f9368132fda39492fa19d8a3180854f7dacdf194"
      define_method(:install) do
        bin.install "shark"
      end
    end
  end

  test do
    system "#{bin}/shark", "--version"
  end
end
